# -*- coding: utf-8 -*-
"""LVADSUSR112_Santhosh_lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CqeCttfO0IXWOiNNRUH65hjX0pjS08gO
"""

import pandas as pd
wine=pd.read_csv('/content/Mall_Customers.csv')
wine

null_values=wine.isnull().sum()

wine.duplicated().sum()

values=wine.describe()

import matplotlib.pyplot as plt
wine.plot(kind='box')

for index in values.columns:
  wine[index].plot(kind='hist')
  plt.xlabel(index)
  plt.show()

import numpy as np
for index in null_values.index:
  try:
    wine[index].replace(np.NaN,values.loc['50%',index],inplace=True)
  except:
    index
wine.describe()
wine.isnull().sum()

wine.duplicated().sum()

wine.drop_duplicates(inplace=True)

wine.duplicated().sum()

q1=values.loc['25%']
q3=values.loc['75%']
iqr=q3-q1
uw=q3+iqr*1.5
lw=q1-iqr*1.5
for index in q3.index:
  for row in wine[(wine[index]>uw[index])|(wine[index]<lw[index])].index:
    wine.loc[row,index]=values.loc['50%',index]

wine.info()

wine.corr()['Spending Score (1-100)']

from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import silhouette_score
le=LabelEncoder()
wine['Gender']=le.fit_transform(wine['Gender'])
wine.corr()['Spending Score (1-100)']

k=range(1,11)
sse=[]
for i in k:
  KM=KMeans(n_clusters=i)
  KM.fit_predict(wine)
  sse.append(KM.inertia_)
plt.plot(k,sse,marker='o')

KNN=KMeans(n_clusters=2)
KNN=KNN.fit(wine)
result=KNN.predict(wine)
labels=KNN.labels_
print(silhouette_score(wine,labels))