# -*- coding: utf-8 -*-
"""LVADSUSR112_Santhosh_lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DkA06tKAq6cvP1MHMy79EnEON1_9dhnS
"""

import pandas as pd
import numpy as np
expenses_df=pd.read_csv("/content/expenses.csv")
expenses_df

expenses_df.isnull().sum()

expenses_df.describe()

import matplotlib.pyplot as plt
expenses_df['charges'].plot(kind='hist')

q3=expenses_df.describe().loc['75%']
q1=expenses_df.describe().loc['25%']
uw=q3+(q3-q1)*1.5
lw=q1-(q3-q1)*1.5

median_bmi=expenses_df.describe().loc['50%','bmi']
median_charges=expenses_df.describe().loc['50%','charges']
for data in expenses_df[((expenses_df['bmi']>uw[1]) | (expenses_df['bmi']<lw[1]))].index:
  expenses_df.loc[data,'bmi']=median_bmi
for data in expenses_df[((expenses_df['charges']>uw[3]) | (expenses_df['charges']<lw[3]))].index:
  expenses_df.loc[data,'charges']=median_charges
expenses_df[((expenses_df['bmi']>uw[1]) | (expenses_df['bmi']<lw[1])|
             (expenses_df['charges']>uw[3])|(expenses_df['charges']<lw[3])) ]
expenses_df['bmi'].replace(np.NaN,median_bmi)

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
expenses_df['region']=le.fit_transform(expenses_df['region'])
expenses_df['sex']=le.fit_transform(expenses_df['sex'])
expenses_df['smoker']=le.fit_transform(expenses_df['smoker'])
expenses_df

expenses_df.corr()

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
LR=LinearRegression()
x_train,x_test,y_train,y_test=train_test_split(expenses_df.iloc[:,:-1],expenses_df.iloc[:,-1],test_size=0.2)
LR=LR.fit(x_train,y_train)
result=LR.predict(x_test)
print(LR.score(x_test,y_test))
print(mean_squared_error(y_test,result))