# -*- coding: utf-8 -*-
"""LVADSUSR112_Santhosh_lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19MtNiBPKBgMfesw5OdRasXJrepbvbEiT
"""

#LAB 3
import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv('/content/seeds.csv')

#Removing null and dupliactes
for index in data.columns:
  print(index)
  data[index].replace(np.NaN,data[index].mean(),inplace=True)
print(data.duplicated().sum())


#Outlier detection
data.info()
print(data.describe())

data.plot(kind='box')
plt.xticks(rotation=90)
plt.show()

for column in data.describe():
  data[column].plot(kind='hist')
  plt.xlabel(column)
  plt.show()

values=data.describe()
Q1=values.loc['25%']
Q3=values.loc['75%']
upper_bound=Q3+(Q3-Q1)*1.5
lower_bound=Q1-(Q3-Q1)*1.5
outlier=[]
for index in Q1.index:
  number=len(data[(data[index]>upper_bound[index])|(data[index]<lower_bound[index])])
  if number>0:
    outlier.append([index,number])
print(outlier)

#Model Building

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score,davies_bouldin_score,calinski_harabasz_score
from sklearn.model_selection import cross_val_score,StratifiedKFold


k=range(1,11)
sse=[]
for i in k:
  RFC=KMeans(n_clusters=i)
  RFC.fit_predict(data)
  sse.append(RFC.inertia_)
plt.plot(k,sse,marker='o')

RFC=KMeans(n_clusters=3)
RFC.fit_predict(data)
labels=RFC.labels_
print(f'Silhoutte Score:{silhouette_score(data,labels)}\nDavies Bouldin Score:{davies_bouldin_score(data,labels)}\nCalinski Harabasz Score:{calinski_harabasz_score(data,labels)}\n')